# Generated by Django 3.2.10 on 2022-06-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_remove_post_description_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='flower.jpg', upload_to='profile_pics'),
        ),
    ]
